### ISSUE TITLE
select2#initSelection was not able to map each "id" to an object from "content"

### ISSUE THREAD

**Issue by NeilAllen** [iStefo/ember-select-2#139]
What does it mean & how do I fix it?

**Comment by NeilAllen** [comment]
hi im kinda having a problem how to implement it with ember data. thank you your plugin is great :D

Actually, I think it's half-baked but it seems stroking your ego gets an answer - what's to do?

**Comment by iStefo** [comment]
If this is how you think you will get a better answer from someone who does not in any way profit from a) writing this addon and b) helping others out when they encounter an error, then I am sorry to have you disappointed.

The source code is actually quite nicely documented on this particular message.

**Comment by gdufford** [comment]
Hi Stefan, I'm also encountering this error, trying to work on a former co-worker's code. I'm going to try something kinda strange and crazy (bear with me), I'm NOT going to be a dickhead and insult you when I need help. What you think, is it crazy enough to work? 

I'm getting the correct value showing in the non-selected menu, but it won't expand and show the content. If you could help me out I'd really appreciate it.

**Comment by NeilAllen** [comment]
Oh! bully for you!

If people are going to put their work forward they should be accountable, ego stroker.

**Comment by iStefo** [comment]
Hi,

Since you seem to be a more considerate human being, let me try to explain this message briefly,:
On startup, ember-select-2 usually has two arrays: One of the selected values and one of the available options. It then tries to find a corresponding object in `options` for each key in `values` (only applies when used with optionValuePath, I believe).
Now, if ember-select-2 is unable to match each value with an underlying object, it sets itself into the disabled state until the options array contains all the items needed (for example because they are loaded lazily from the server).

I can only advise you to manually match those arrays in the case where your select component locks itself and try to figure out why there would be a mismatch between the options and the (selected) values.
Of course there may also be a bug that causes this error to appear for a different reason, but I have never experienced it any other way than described above.
