### ISSUE TITLE
Memory leak  in Select2 plugin

### ISSUE THREAD

**Issue by muthuraja** [iStefo/ember-select-2#143]
Hi,
Events not properly detached. Its eating lot of memory. Try to Fix it. 
![select2](https://cloud.githubusercontent.com/assets/26075/21353320/8f0f5a44-c6eb-11e6-8145-4b8ab431b3fb.png)

**Comment by iStefo** [comment]
I know that there are problems with memory management because it is generally difficult to to bind between a complex jQuery component and an ember component without leaking any memory but keeping all the data binding benefits.
I currently don't have any time for this problem and this project is discontinued in favour of ember-power-select anyways, but if you need this fix, please try to achieve it yourself and issue a pull-request.
