### ISSUE TITLE
Check if dropdown is selected from the promised value when the binding value property is a promise

### ISSUE THREAD

**Issue by Jcarlosjunior** [iStefo/ember-select-2#30]
`{{select-2 value=myValue content=myContent optionLabelPath='name'  allowClear=true}}`

If "myValue" in the example above is a "belongsTo" in ember-data, even when it doenst have a content it's value is not null or any falsy value, because the property it's a promise that resolves to its promised (real) value. 
I think if the ember-select-2 could see if the property is a promise and check if there is a promised value to set the dropdown as selected or not.

**Comment by jpaas** [comment]
I swear this used to work for me but has recently regressed. Perhaps because I've been upleveling ember and ember data?

I have a select for a hasOne relationship called 'resource' that looks like this:

```handlebars
          {{select-2
          optionLabelPath='name'
          placeholder=(format-message (intl-get 'attributes.resource-node.resource'))
          query='queryResources'
          value=model.resource
          }}
```
 My select renders fine if model.resource is null, but if it has a value, the select doesn't render even after the promise has been resolved.

I'm using:

* ember-select-2 1.3.0
* ember 1.13.4
* ember-data 1.13.5
